caroline-jeffra/jamfinder

- config/environments/production.rb
configuration change to force https in production. Single line within config/environments/production.rb was uncommented to activate it and local testing shows no navigation issues.
> updated config/environments/production.rb file to force_ssl = true

- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/layouts/_search.html.erb
- app/views/shared/_navbar.html.erb
homogenize fonts and colors prior to further development
> Custom styling setup

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/registrations_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/pages/dashboard.html.erb
- config/initializers/devise.rb
- config/routes.rb
- test/controllers/registrations_controller_test.rb
Completed basic form with placeholders instead of labels.
Before the user gets saved to the db, its display_name gets set to the first_name provided on signup.
Once signup is complete, user gets redirected to their dashboard
**TODO:** forms are a bit cramped, potentially adjustments to styling should be made
> Devise forms

- app/models/user.rb
The server started to crash after the last merge. It is a simple correction
> Solving problem on user model

- app/views/layouts/_user_summary.html.erb
last changes of inserting fontawesome placeholders in card
> User card partial - last bit delayed by errors

- app/assets/stylesheets/application.scss
- app/views/pages/home.html.erb
- app/views/profiles/index.html.erb
- app/views/shared/_navbar.html.erb
first round of fixing biggest bugs to the site width issues - more to come later
> changed vh to vw values in width added to view and home pages

- app/views/pages/home.html.erb
- app/views/profiles/index.html.erb
- app/views/shared/_navbar.html.erb
the 7vh downward offset now applied sitewide by adding it to the navbar partial itself instead of manually page by page
> Navbar height offset

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
These changes have led to issues with the upper portion of the pages#index page which need to be resolved. Will address these later. navbar is now sticking to top and offsetting content
> navbar sticking correctly - cascades issues with profiles#index

- app/views/layouts/_user_summary.html.erb
I replaced the TODO with the user's address in the cards. Next week we can update it with something from geocoder
> insert card address

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/shared/_navbar.html.erb
corrected display color of 'a' element in a primary button (was pink, now white) and added padding to left and right of button text so that border radius curve is not encroaching on text. border radius curve of buttons is now an uninterrupted curve
> Button primary text

- app/models/user.rb
sets default images to prevent app crash
> Default user images on create

- app/models/user.rb
- app/views/profiles/index.html.erb
This search field works with users' displays_name and location, genre, instruments and categories.
The input can be mixed or incomplete.
When there are no matches, a message renders in the view.
> Implement search field. final

- app/views/pages/dashboard.html.erb
- app/views/shared/_user_dash_card.html.erb
implement for self profile views: 
`<%= render 'shared/user_dash_card', user: @user %>`
> created partial for abbreviated user card

- app/views/shared/_navbar.html.erb
position and sizing of elements within navbar has been corrected. border around avatar removed
> Navbar styling corrections

- app/assets/stylesheets/application.scss
- app/views/pages/dashboard.html.erb
- app/views/shared/_navbar.html.erb
updated .sticky-class and created .sticky-class-2 to maintain profile/scheduled jams link position at top of dashboard pages. created default message to display when a user does not have any scheduled jams
> Sticky link banner

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/_search_form.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
made banner better size, placed search bar correctly, resized search bar input + text, updated toggleable element color/size, made page content scrollable for home + dash
> Banner landing page styling and associated changes

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
login and sign up pages now match site style and have consistent button styling/sizing. flash alerts match color scheme and have readable font size.
> Auth pages styling

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_profiles_list.scss
- app/views/layouts/_mapbox.html.erb
- app/views/profiles/index.html.erb
Seems to have sorted it.
Created a couple of custom classes and only changed styling within profiles/index so it should not create conflicts with any other view 
https://github.com/caroline-jeffra/jamfinder/assets/5818940/44f815ec-ff27-4590-a477-bc48f68a9630
> Responsive(⁉️) profiles index without weird scrolling???

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_upload_photo.scss
- app/controllers/profiles_controller.rb
- app/javascript/controllers/photo_upload_controller.js
- app/views/layouts/_show_images.html.erb
- app/views/profiles/_imageform.html.erb
> Add images button to Cloudinary 

- app/assets/stylesheets/components/_alert.scss
- app/views/layouts/application.html.erb
meta tagging work, has not broken anything
> Meta tagging setup

- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_navbar_auth.html.erb
- app/views/shared/_navbar_search.html.erb
Stopped avatar from moving when navbar expands and contracts
divided logic into authenticated vs non authenticated users - fewer conditional statements but two separate navbar partials.
> improved navbar
